app = "chat-service-academy"
primary_region = "gru"

[env]
SPRING_PROFILES_ACTIVE = "prod"
LLM_PROVIDER = "openrouter"
DOCUMENT_SERVICE_URL = "https://document-service-academy.fly.dev"

SERVER_PORT = "8080"
SERVER_ADDRESS = "0.0.0.0"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2


  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[[vm]]
memory = "1024mb"
cpu_kind = "shared"
cpus = 1
