package com.academy.chatservice.model;

public enum LearningEvidenceMetric {
    DOCUMENTS_ANALYZED,
    EXERCISES_DETECTED,
    RELEVANT_INTERACTIONS,
    STUDY_TIME_MINUTES,
    EXERCISES_ABANDONED,
    EXERCISES_SOLVED_WITHOUT_HELP,
    EXERCISES_SOLVED_WITH_HELP,
    SMART_WHITEBOARD_USAGE
}
